### PR TITLE
[v2] Fix anchor navigation in panel headers

### LINKED ISSUE #1071: Anchor navigation in panel not working properly with fixed header
**Tell us about your environment**

* **MarkBind Version:**2.11.0

**What did you do? Please include the actual source code causing the issue.**
1. Fix the header with `<header class="header-fixed">` in `header.md`
2. Include the following content
```html
<panel header="## Hello">
</panel>
```

**What did you expect to happen?**

Anchor navigation on "Hello" should work properly.

**What actually happened? Please include the actual, raw output.**

Clicking the anchor would place the title under the top navbar.

### LINKED ISSUE #1104: Heading hidden when clicking pageNav
Happens when the heading is in a panel header and the topNav is in fixed mode.
pageNav-glitch

### PR DESCRIPTION
**Pull request by le0tan**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Documentation update
• [X] Bug fix

Replaces #1145 #1187 
Fixes #1104 Fixes #1071

**What changes did you make? (Give an overview)**

Move span generation to a plugin during build time. Add `::before` to panel card containers to make navigation work properly on panel headers.

**Provide some example code that this change will affect:**

na

**Is there anything you'd like reviewers to focus on?**

Test if the panel functions are broken in any way.

**Testing instructions:**

na

**Proposed commit message: (wrap lines at 72 characters)**

To avoid dynamically injecting lots of dummy spans in a document with
many headings, let's generate these spans at build time.

To make anchor navigation function properly on panel headers, let's
introduce ::before element to `card-container` to make space for the
fixed top nav.

### CODE REVIEW

File: src/lib/markbind/src/parser.js [hunk 1]
```diff
@@ -353,6 +353,11 @@ class Parser {
 
     componentParser.postParseComponents(node, this._onError);
 
+    // If a fixed header is applied to this page, generate dummy spans as anchor points
+    if (config.fixedHeader && (/^h[1-6]$/).test(node.name) && node.attribs.id) {
```
Comment (ang-zeyu) [inline src/lib/markbind/src/parser.js:357]: since `(/^h[1-6]$/).test(node.name)` is used twice in the method, perhaps we could extract that out into a variable `isHeaderTag`

File: src/Page.js [hunk 2]
```diff
@@ -927,7 +940,12 @@ class Page {
         .then(result => this.insertFooterFile(result))
         .then(result => Page.insertTemporaryStyles(result))
         .then(result => markbinder.resolveBaseUrl(result, fileConfig))
-        .then(result => markbinder.render(result, this.sourcePath, fileConfig))
+        .then((result) => {
+          // this.fixedHeader may be updated in previous step insertHeaderFile
+          // we need to reflect the update and pass it to the renderer, if necessary
+          fileConfig.fixedHeader = this.fixedHeader;
```
Comment (ang-zeyu) [inline src/Page.js:946]: should we pass `fileConfig` into `insertHeaderFile` instead? Best to keep related code close together, would remove the need for the comment as well

**Comment by ang-zeyu** [comment]
Some conflicts @le0tan

**Comment by le0tan** [comment]
@ang-zeyu looks like you removed some pointer events from `setupAnchors`. This function is necessary in all cases as it injects the events where hovering over the heading or anchor will make the anchor icon visible. Do tell me if I misunderstood anything.

**Comment by ang-zeyu** [comment]
> @ang-zeyu looks like you removed some pointer events from `setupAnchors`. This function is necessary in all cases as it injects the events where hovering over the heading or anchor will make the anchor icon visible. Do tell me if I misunderstood anything.

Refer to the second commit in #1129. It's moved to plugin css ( new feature )

**Comment by le0tan** [comment]
@ang-zeyu got it and I changed my code accordingly, can you take a look?

**Comment by ang-zeyu** [comment]
@le0tan there's still a large amount of conflicts, mostly from previous versions

File: docs/userGuide/syntax/headers.mbdf [hunk 3]
```diff
@@ -23,6 +23,17 @@ In the page that you want to include the header:
 ```
 </div>
 
+You can fix the header to be always on the top by add `class="header-fixed"` attribute to the `<header>` tag of your header file:
+
+{{ icon_example }}
+**`_markbind/headers/`**`header.md`:
```
Comment (ang-zeyu) [inline docs/userGuide/syntax/headers.mbdf:29]: Since we are documenting this now, would be a good point to get @damithc's opinion on fixed navbar usage.
( maybe something simpler like `<header fixed>`? 😮  )

File: asset/js/setup.js [hunk 4]
```diff
@@ -32,20 +32,18 @@ function setupAnchorsForFixedNavbar() {
   jQuery('#content-wrapper').css('padding-top', `calc(${headerHeight}px)`);
```
Comment (ang-zeyu) [inline asset/js/setup.js:32]: would it be possible to just insert the padding for the main container and not its 3 sub containers?
fixedheader

File: docs/userGuide/syntax/headers.mbdf (hunk 3 above)
Comment (damithc) [reply docs/userGuide/syntax/headers.mbdf:29]: Yes I prefer a simpler `fixed` if there are no other drawbacks.

File: asset/js/setup.js (hunk 4 above)
Comment (le0tan) [reply asset/js/setup.js:32]: As far as I'm concerned it doesn't work...

Comment (ang-zeyu) [reply asset/js/setup.js:32]: ok, might be better to leave it this way as well: `.css('nav-inner')` needs to be offsetted with the original padding

navbarpadding

Comment (le0tan) [reply asset/js/setup.js:32]: just did that, wondering if we need to add `1rem` to `content-wrapper` as well, but probably better leave it as a future first timer issue?

Comment (ang-zeyu) [reply asset/js/setup.js:32]: Good idea, would make it seem less squeezed to the top. Let's leave it as a first timer issue then, though if you want to include it here it'd be nice as well
