### PR TITLE
Fix searchbar overflowing for mobile

### LINKED ISSUE #2002: Search bar overflows on mobile devices
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

_No response_

### Tell us about your environment

Windows 10

### MarkBind version

4.0.0

### What did you do? Describe the bug

Go to https://markbind-master.netlify.app/index.html on mobile devices, the search bar exceeds the screen width.

image

Let's try to resolve this before releasing 4.0.1.

### Steps to reproduce

Most likely due to setting a [`min-width` in `Searchbar.vue`](https://github.com/MarkBind/markbind/blob/master/packages/vue-components/src/Searchbar.vue#L266)

### Expected behavior

Search bar should not overflow

### Actual behavior

Search bar exceeds the screen width as shown above.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by domlimm**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [X] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Fixes #2002.

Added a media query to handle for mobile screens (not too familiar but `max-width: 768px` seems to suffice).

In the media query, we set the `min-width` and `max-width` to follow the styling of the current prod's search bar.

Also, with reference to PR #1959 to not interfere with the implementation of it, and follow it by giving the search bar a `min-width` and `max-width`.

**Anything you'd like to highlight/discuss:**
NIL

**Testing instructions:**
Served locally.

**Proposed commit message: (wrap lines at 72 characters)**
Fix searchbar overflow for mobile screens

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [ ] Linked all related issues
- [ ] No unrelated changes

### CODE REVIEW

File: packages/vue-components/src/Searchbar.vue [hunk 1]
```diff
@@ -267,6 +267,13 @@ export default {
         max-width: 25.4em; /* twice of min-width, to accommodate a range of lengths */
     }
 
+    @media screen and (max-width: 768px) {
+      .form-control {
+          min-width: 8em;
+          max-width: 16em; /* twice of min-width, to accommodate a range of lengths */
+        }
```
Comment (jonahtanjz) [inline packages/vue-components/src/Searchbar.vue:274]: Some styling issue here causing the linting to fail. You may want to run `npm run lintfix` to help lint the code next time :)

**Review by jonahtanjz — COMMENTED** [review]
Thanks @domlimm 👍 

You may also want to add a media query for tablets (>767px and <879px). Currently the search bar is still overflowing for longer placeholders for the above range.

image

**Comment by domlimm** [comment]
Hey @jonahtanjz! Thanks for reviewing! And yes, slipped my mind to test for tablets 😅 Will add it in now! 👍🏻

File: packages/vue-components/src/Searchbar.vue (hunk 1 above)
Comment (domlimm) [reply packages/vue-components/src/Searchbar.vue:274]: Yes, that's right! Got to make running `npm run lint` a habit. Didn't realise the styles are using 4 spaces instead of 2. Thanks for the advice!!

**Comment by domlimm** [comment]
@jonahtanjz Hey Jonah! Sorry that took awhile, was trying out what works best. FYI, if it's still overflowing when you are testing, you could refresh the page and it should work accordingly.

Thank you, appreciate it! 😄

**Review by jonahtanjz — APPROVED** [review]
Thanks for making the changes @domlimm!

LGTM 👍

**Review by tlylt — COMMENTED** [review]
Not sure if I am missing anything, it seems to overflow after 767px:
image

**Comment by domlimm** [comment]
@tlylt Yes, same behaviour at my end. Attached a demo below.

Maybe might have to tweak the range.

https://user-images.githubusercontent.com/46486515/184519911-0b49a1b4-27d8-4b3f-bb13-a7dac8450294.mp4

**Comment by jonahtanjz** [comment]
@tlylt @domlimm 

I think this has more to do with the issue #1699. The width of the search bar will have to vary depending on the number of items in the navbar menu. There are a couple of solutions discussed here https://github.com/MarkBind/markbind/pull/1760#pullrequestreview-880843001 if are interested. This can be done in another PR :)

File: packages/vue-components/src/Searchbar.vue [hunk 2]
```diff
@@ -267,6 +267,29 @@ export default {
...
 
+    @media screen and (max-width: 767px) {
+        .form-control {
+            min-width: 8em;
+            max-width: 16em; /* twice of min-width, to accommodate a range of lengths */
+        }
+    }
+
+    /* For general tablets in portrait e.g. iPad */
+    @media screen and (min-width: 768px) and (max-width: 878px) and (orientation: portrait) {
```
Comment (jonahtanjz) [inline packages/vue-components/src/Searchbar.vue:278]: How about combining this with the above query since they have the same property?

```.js
@media screen and (max-width: 767px), screen and (min-width: 768px) and (max-width: 878px) and (orientation: portrait) {
        .form-control {
            min-width: 8em;
            max-width: 16em; /* twice of min-width, to accommodate a range of lengths */
        }
}
```

Comment (domlimm) [reply packages/vue-components/src/Searchbar.vue:278]: Thanks Jonah! Will make the change.
