### PR TITLE
[WIP] Fix default html index page not detected by watchers

### LINKED ISSUE #1682: Flags in `markbind serve` does not seem to work. Specifically `-f` and `-d`
**Tell us about your environment**
Windows 10
VScode

**MarkBind Version:**
Latest version

**What did you do? Please include the actual source code causing the issue.**
- Create a test template
- Run `markbind serve -d` to run the markbind server locally. 
- Edit the markbind template and save the file.

Repeat and test for the `-f` flag.

**What did you expect to happen?**
Expected the website to reload and reflect changes on the live webpage.

**What actually happened? Please include the actual, raw output.**
The page does not reload and instead stays the same

Example of what actually happened for the `-d` flag
StaleReload

### PR DESCRIPTION
**Pull request by aaronsms**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [X] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] Others, please explain:

Fixes #1682 

**Overview of changes:**
This PR fixed the handling of default index.html page that is not detected by live server module. The current diagnosis is that "*/" is compared with "*/index.html" yielding negative results.

**Anything you'd like to highlight / discuss:**
This is a PR in relation to CS3281 application. This PR is still work in progress, as tests are yet to be introduced to the live server module.

**Testing instructions:**

0. `mkdir test && cd test`
1. `markbind init`
2. `markbind serve -d`
3. Edit the index.md file and the changes will be reflected on the browser.

**Proposed commit message: (wrap lines at 72 characters)**
Fix default html index page not detected by watchers

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements (not relevant)
- [ ] Added tests for bug fixes or features (work in progress)
- [X] Linked all related issues
- [ ] No unrelated changes

### CODE REVIEW

File: packages/cli/src/lib/live-server/index.js [hunk 1]
```diff
@@ -421,8 +421,22 @@ LiveServer.start = function(options) {
     }
 
     // Only reload active tabs if the changed file is opened in one of them
+    const handleHtmlUrl = (url) => {
```
Comment (ang-zeyu) [inline packages/cli/src/lib/live-server/index.js:424]:
```suggestion
    const normalizeUrl = (url) => {
```

**Review by ang-zeyu — COMMENTED** [review]
Diagnosis and fix lgtm!

Pinging @ryoarmanda for a second look as I might have forgotten some specifics here.

---

One tiny naming suggestion as well:

File: packages/cli/src/lib/live-server/index.js [hunk 2]
```diff
@@ -421,8 +421,22 @@ LiveServer.start = function(options) {
...
+      if (!url || url.length === 0) {
+        return "index.html";
+      }
+
+      if (url.endsWith('.html')) {
```
Comment (ryoarmanda) [inline packages/cli/src/lib/live-server/index.js:429]: Use the more apt `path.extname(url)` to get the file extension instead

File: packages/cli/src/lib/live-server/index.js [hunk 3]
```diff
@@ -421,8 +421,22 @@ LiveServer.start = function(options) {
...
+      }
+
+      return url.replace(/\/$/g, '').concat('/index.html');
+    };
+
     let normalizedPath = fsUtil.ensurePosix(path.relative(root, changePath));
-    if (LiveServer.activeTabs.some(tab => tab.client && tab.url === normalizedPath)) {
+    if (LiveServer.activeTabs.some(tab => {
+      return tab.client && handleHtmlUrl(tab.url) === handleHtmlUrl(normalizedPath);
+    })) {
```
Comment (ryoarmanda) [inline packages/cli/src/lib/live-server/index.js:439]: I think only the call for `tab.url` is necessary, as that is the only variable that is possible to have the `*/` form. `normalizedPath` refers to the normalized path of an existing file that was just changed, so it most likely never holds the `*/` form, and therefore the call on it would be doing nothing.

I'd opt to use implicit return instead as it is just a short single return statement.

**Review by ryoarmanda — COMMENTED** [review]
Overall, lgtm! I just have a couple of nits here, nothing big

File: packages/cli/src/lib/live-server/index.js (hunk 1 above)
Comment (aaronsms) [reply packages/cli/src/lib/live-server/index.js]: Fixed.

File: packages/cli/src/lib/live-server/index.js (hunk 3 above)
Comment (aaronsms) [reply packages/cli/src/lib/live-server/index.js]: Thanks for the suggestions, fixed all the pointed issues.

File: packages/cli/src/lib/live-server/index.js [hunk 4]
```diff
@@ -421,8 +421,22 @@ LiveServer.start = function(options) {
...
+    const handleHtmlUrl = (url) => {
+      if (!url || url.length === 0) {
+        return "index.html";
+      }
+
+      if (url.endsWith('.html')) {
+        return url;
+      }
+
+      return url.replace(/\/$/g, '').concat('/index.html');
```
[the remark this answers is not in the document]
Comment (ang-zeyu) [reply packages/cli/src/lib/live-server/index.js]: Thanks for making the changes! @aaronsms 

Just one more issue:

this should be `path.posix.join`, as `path` is os specific for handling the respective filesystems.

E.g. on windows:
```
> path.join('foo/bar/xx', 'index.html')
becomes this
'foo\\bar\\xx\\index.html'
```

**Review by ang-zeyu — APPROVED** [review]
Lgtm!
