### PR TITLE
Fix intra-link warning when using query parameters

### LINKED ISSUE #2768: Invalid intra-link warning given when the link has URL parameters
Example: 
>warn: You might have an invalid intra-link! Ignore this warning if it was intended.
'/companion-app/index.html?cv-focus=JTVCJTdCJ

`/companion-app/index.html` is a valid page. I suspect the URL parameter `?cv-focus=JTVCJTdCJ` is triggering the warning. Perhaps we should ignore the URL parameters when testing for invalid links?

### PR DESCRIPTION
**Pull request by Harjun751**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

Resolves #2768

**Overview of changes:**
Prevents the invalid intra-site warning by preventing query parameters from being validated. Adds linkProcessor tests for this case.

**Anything you'd like to highlight/discuss:**

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**

Fix invalid intra-link warning when using query parameters

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [x] Added tests for bug fixes or features
- [x] Linked all related issues
- [ ] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [x] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

### CODE REVIEW

**Review by gerteck — CHANGES_REQUESTED** [review]
Thank you for your help on this 👍

File: packages/core/src/html/linkProcessor.ts [hunk 1]
```diff
@@ -184,6 +184,9 @@ export function validateIntraLink(resourcePath: string,
     hash = resourcePathUrl.hash.substring(1);
     // remove hash portion (if any) in the resourcePath
     resourcePath = resourcePathUrl.pathname; // eslint-disable-line no-param-reassign
+  } else if (resourcePathUrl.query) {
```
[the remark this answers is not in the document]
Comment (Harjun751) [reply packages/core/src/html/linkProcessor.ts]: Ah yea, makes sense. Incorporated changes as per your suggestion!

File: packages/core/src/html/linkProcessor.ts [hunk 2]
```diff
@@ -179,12 +179,8 @@ export function validateIntraLink(resourcePath: string,
   resourcePath = urlUtil.stripBaseUrl(resourcePath, config.baseUrl); // eslint-disable-line no-param-reassign
```
Comment (gerteck) [inline packages/core/src/html/linkProcessor.ts]: Could you help to refactor this to not rely on // eslint-disable-line no-param-reassign
* i.e. remove param reassignment, create new variable with a appropriate name instead

Note that as the strings are primitive and passed into the function (not an object), there should be no side effect of the code, so less chance of regression.

Additionally, if you would like, you could also help to reduce complexity of this method but extracting out some helper methods, such as 
* `validateDirectoryLink()`
*  `validateHtmlLink()`
etc etc, but you can tackle that in a separate PR.

Thanks!

Comment (Harjun751) [reply packages/core/src/html/linkProcessor.ts]: Sure!
