### PR TITLE
Fix error when deploying

### LINKED ISSUE #1354: Error when deploying
Error during `markbind deploy`
The deployment seems to succeed though

>v2.16.0                                                                            error:  message=Cannot read property 'trim' of undefined, stack=TypeError: Cannot r ead property 'trim' of undefined                                                        at C:\Users\damithch\AppData\Roaming\npm\node_modules\markbind-cli\node_modules \@markbind\core\src\Site\index.js:1385:34                                               at tryCatcher (C:\Users\damithch\AppData\Roaming\npm\node_modules\markbind-cli\ node_modules\bluebird\js\release\util.js:16:23)                                         at Promise._settlePromiseFromHandler (C:\Users\damithch\AppData\Roaming\npm\nod e_modules\markbind-cli\node_modules\bluebird\js\release\promise.js:547:31)              at Promise._settlePromise (C:\Users\damithch\AppData\Roaming\npm\node_modules\m arkbind-cli\node_modules\bluebird\js\release\promise.js:604:18)                         at Promise._settlePromise0 (C:\Users\damithch\AppData\Roaming\npm\node_modules\ markbind-cli\node_modules\bluebird\js\release\promise.js:649:10)                        at Promise._settlePromises (C:\Users\damithch\AppData\Roaming\npm\node_modules\ markbind-cli\node_modules\bluebird\js\release\promise.js:729:18)                        at Promise._fulfill (C:\Users\damithch\AppData\Roaming\npm\node_modules\markbin d-cli\node_modules\bluebird\js\release\promise.js:673:18)                               at PromiseArray._resolve (C:\Users\damithch\AppData\Roaming\npm\node_modules\ma rkbind-cli\node_modules\bluebird\js\release\promise_array.js:127:19)                    at PromiseArray._promiseFulfilled (C:\Users\damithch\AppData\Roaming\npm\node_m odules\markbind-cli\node_modules\bluebird\js\release\promise_array.js:145:14)           at Promise._settlePromise (C:\Users\damithch\AppData\Roaming\npm\node_modules\m arkbind-cli\node_modules\bluebird\js\release\promise.js:609:26)                         at Promise._settlePromise0 (C:\Users\damithch\AppData\Roaming\npm\node_modules\ markbind-cli\node_modules\bluebird\js\release\promise.js:649:10)                        at Promise._settlePromises (C:\Users\damithch\AppData\Roaming\npm\node_modules\ markbind-cli\node_modules\bluebird\js\release\promise.js:729:18)                        at _drainQueueStep (C:\Users\damithch\AppData\Roaming\npm\node_modules\markbind -cli\node_modules\bluebird\js\release\async.js:93:12)                                   at _drainQueue (C:\Users\damithch\AppData\Roaming\npm\node_modules\markbind-cli \node_modules\bluebird\js\release\async.js:86:9)                                        at Async._drainQueues (C:\Users\damithch\AppData\Roaming\npm\node_modules\markb ind-cli\node_modules\bluebird\js\release\async.js:102:5)                                at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\damithch\AppData\Roa ming\npm\node_modules\markbind-cli\node_modules\bluebird\js\release\async.js:15:14)
--

### PR DESCRIPTION
**Pull request by KendrickAng**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Bug fix

Fixes #1354 , while addressing an incorrect implementation from #1329 

**What is the rationale for this request?**
To fix a bug #1354 caused when running `markbind deploy`.

Additionally, this PR fixes a prior issue from #1329 , where an incorrect URL would be displayed when no CNAME exists in the website being deployed (no custom URL is being used for gh-pages). In that case, the incorrect URL was being constructed 
from the repository name. 
(If I have a repository Orbital3 the old URL would be `https://kendrickang.github.io/orbital3.git/` when it should have been `https://kendrickang.github.io/Orbital3/`)

**What changes did you make? (Give an overview)**
The case that CNAME was undefined was not being handled. In that case, a gh-pages link should be reconstructed based on the repo name. This PR also addresses an further issue where the file extension `.git` was not being stripped from the generated URL.

**Provide some example code that this change will affect:**

```js
const cname = results[0];
const remoteUrl = results[1];
if (cname) {
   return cname.trim();
} else if (repo) {
  return constructGhPagesUrl(repo);
}
return constructGhPagesUrl(remoteUrl.trim());

// another separate snippet
const repoNameWithExt = parts[parts.length - 1];
const repoName = repoNameWithExt.substring(0, repoNameWithExt.lastIndexOf('.'));
```

**Is there anything you'd like reviewers to focus on?**

**Testing instructions:**
1. Generate any empty test site with a remote github repo (so gh-pages can be used).
2. Add the repo name to baseUrl in `site.json`
3. Run `markbind deploy` and verify correctness

**Proposed commit message: (wrap lines at 72 characters)**
Fix error when deploying and correct generated URL

### CODE REVIEW

File: packages/core/src/Site/index.js [hunk 1]
```diff
@@ -1313,16 +1313,17 @@ class Site {
       if (!remoteUrl) {
         return null;
       }
+      const parts = remoteUrl.split('/');
       if (remoteUrl.startsWith(HTTPS_PREAMBLE)) {
         // https://github.com/<name|org>/<repo>.git (HTTPS)
-        const parts = remoteUrl.split('/');
-        const repoName = parts[parts.length - 1].toLowerCase();
+        const repoNameWithExt = parts[parts.length - 1];
+        const repoName = repoNameWithExt.substring(0, repoNameWithExt.lastIndexOf('.'));
```
Comment (ang-zeyu) [inline packages/core/src/Site/index.js:1320]: hmm what is the new `.lastIndexOf('.')` for? (and removal of `toLowerCase`)

Comment (KendrickAng) [reply packages/core/src/Site/index.js:1320]: since repoName would be something like `myrepo.git` (since `parts` is something like ['https', ..., myrepo.git']), in order to generate a correct website link the `.git` should be stripped, which I didn't do before.

As for the removal of toLowerCase, I discovered that the repository name would be directly used in the gh-pages url, so if I have a repository `Orbital3` my URL would be `https://kendrickang.github.io/Orbital3/` --> then .toLowerCase() produce `https://kendrickang.github.io/orbital3/`, which would be incorrect.

I believe this wasn't found in my testing when I wrote this because I only explicitly tested for when CNAME was present (whereas this block is only run when CNAME isn't present)

Comment (ang-zeyu) [reply packages/core/src/Site/index.js:1320]: thanks for the explanation! I'm not opposed to having these fixes here as well since its deploy url related too.
Let's change the commit message title and body accordingly to reflect the changes here though, in case anyone wonders what the changes are for

Comment (KendrickAng) [reply packages/core/src/Site/index.js:1320]: done!

**Review by ang-zeyu — APPROVED** [review]
