### PR TITLE
Fix trim not working when including fragments

### LINKED ISSUE #673: include/trim doesn't trim blank lines
v1.17.2

Current:

`foo.mbd`:
```html
<span id="bar">

    abc

</span>
```

`x<include src="foo.md#bar" inline trim/>x` should result in `xabcx` but results in the below instead:
```
x
abc
x
```

### PR DESCRIPTION
**Pull request by marvinchin**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [x] Bug fix

Fixes #673.

**What is the rationale for this request?**

Trim was not working when including fragments.

**What changes did you make? (Give an overview)**

The error was caused because we trimmed only the **file content** when the trim attribute is present. However, the actual content in the fragment is not trimmed.

This PR ensures that the trim method is called on the content that will actually be included.

**Provide some example code that this change will affect:**

**Source**:
foo.md
```md
x<include src="bar.md#fragment" trim inline />x
```

bar.md
```
<span id="fragment">

  abc

</span>
```

**Output**:
```
xabcx
```

**Testing instructions:**
The example in #673 should now work.

### CODE REVIEW

File: src/lib/markbind/src/parser.js [hunk 1]
```diff
@@ -305,14 +305,12 @@ Parser.prototype._preprocess = function (node, context, config) {
     delete element.attribs.inline;
     delete element.attribs.trim;
 
-    fileContent = isTrim ? fileContent.trim() : fileContent;
-
     if (includeSrc.hash) {
       // directly get segment from the src
       const segmentSrc = cheerio.parseHTML(fileContent, true);
       const $ = cheerio.load(segmentSrc);
       const htmlContent = $(includeSrc.hash).html();
```
Comment (Xenonym) [inline src/lib/markbind/src/parser.js]: Could we call this variable `fragmentContent` instead? I think trying to mentally differentiate between `htmlContent` and `fileContent` is confusing.

File: test/functional/test_site/testTrimIncludeFragment.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+<span id="fragment">
+
+    Fragment with leading spaces and newline
+
+</span>
```
Comment (Chng-Zhi-Xuan) [inline test/functional/test_site/testTrimIncludeFragment.md]: Small inconsistency, fragment files have the extension of `.mbdf` instead of `.mb` (given that you explicitly named the file a fragment).

File: test/functional/test_site/index.md [hunk 3]
```diff
@@ -133,6 +133,10 @@ tags: ["tag-frontmatter-shown", "tag-included-file", "+tag-exp*", "-tag-exp-hidd
 
 ## <include src="testTrimInclude.md" trim inline />
 
+# Trimmed include fragment
```
Comment (Xenonym) [inline test/functional/test_site/index.md]: Could this test be better written as a `parser.js` unit test?

File: test/functional/test_site/index.md [hunk 4]
```diff
@@ -133,6 +133,10 @@ tags: ["tag-frontmatter-shown", "tag-included-file", "+tag-exp*", "-tag-exp-hidd
...
+
+## Before <include src="testTrimIncludeFragment.md#fragment" trim inline /> After
```
Comment (Xenonym) [inline test/functional/test_site/index.md]: Could we make the Before and After parts more visually distinct? For example:
```
Before | <include src="testTrimIncludeFragment.md#fragment" trim inline /> | After
```
or `Before` and `After` could be in a different colour?

**Comment by marvinchin** [comment]
@Xenonym @Chng-Zhi-Xuan I've updated the PR based on your comments 🙂

**Comment by yamgent** [comment]
Propose a merge commit message.

**Comment by marvinchin** [comment]
**Commit Message:**
```
Fix trim not working when including fragments

When a fragment is included with the trim attribute specified, the content remains untrimmed.

The error was caused because only the file content is trimmed when the trim attribute is present. However, the actual content in the fragment is not trimmed.

Let's update the parser to ensure that the actual content to be included is trimmed.
```

**Comment by yamgent** [comment]
Amended your commit message to wrap at 72 characters + make it more concise.

```
Fix trim not working when including fragments

The trim attribute only works when including an entire file. When a
fragment is included instead with the trim attribute specified, the
content remains untrimmed.

Let's fix the parser to ensure that included fragments are also trimmed.
```
