### PR TITLE
Gitignore page-vue-render.js files in CLI Functional Tests

### LINKED ISSUE #2623: Gitignore Vue Render Files for Diff Testing for greater efficiency
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

https://github.com/MarkBind/markbind/issues/1637 - Test Site Improvements
https://github.com/MarkBind/markbind/issues/2631 - Modularize Snapshot Tests

### Tell us about your environment

Win 11

### MarkBind version

5.3.3

### Describe the bug and the steps to reproduce it

See action here: https://github.com/MarkBind/markbind/actions/runs/13703858478/job/38324234697

Image

Noticed it on my local computer as well. Need to ctrl-c locally if tests fail to end. Only happens to certain tests failing.

Actions ran were only ultimately cancelled because a new commit was pushed over it. ( Members by default do not have access writes to cancel workflows).

Think it is for `packages/cli` tests, as they were the only ones that did not run to completion. Unsure if it is due running diff between expected site files and generated files that takes very long, which then it would actually stop, but just take very long.

### Expected behavior

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by gerteck**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [x] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**

Fixes #2623 
Partially Addresses #1637 (See last bullet point)

This PR does basically 3 things.

1. Update `compare.js` function to skip comparison check for PageVueRenderFiles
2. Delete all `.page-vue-render.js` files from in `expected` snapshots
3. Add `.page-vue-render.js` to gitignores to prevent it from being commited during future `updatetest`

Will need help to verify correctness of changes and no unrelated changes or regressions. Thank you! 

**Anything you'd like to highlight/discuss:**

The `*.page-vue-render.js` files that exist in expected snapshots for CLI functional tests have diffs that are unreadable. 

This PR removes diff checking for these files (in `compare.js`), adds gitignore to prevent these files from being unnecessarily committed during snapshot updates and removes the associated render files from the repository.

1. Reduces bloat in expected test files for CLI snapshot testing.
5. Removes unreadable non-value adding changes to the render function during snapshot updates in relevant future PRs  

**Testing instructions:**

Automated tests should work and pass, in particular, CLI functional tests.

**Proposed commit message: (wrap lines at 72 characters)**

Remove page-vue-render.js files from test

*.page-vue-render.js files that exist in expected snapshots for CLI
functional tests have diffs that are unreadable. 

Remove diff checking for these files, and add gitignore to
prevent files from being unnecessarily committed.

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [ ] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

### CODE REVIEW

File: packages/cli/test/functional/testUtil/compare.js [hunk 1]
```diff
@@ -37,6 +51,11 @@ function compare(root, expectedSiteRelativePath = 'expected', siteRelativePath =
   let expectedPaths = walkSync(expectedDirectory, { directories: false });
   let actualPaths = walkSync(actualDirectory, { directories: false });
 
+  // Vue render JS files (*.page-vue-render.js) are not committed to version control,
+  // so we exclude them from the comparison to avoid false positive diffs.
+  // Note: Every non-includes .html file has a corresponding js render binary file
+  actualPaths = filterPageVueRenderFiles(actualPaths);
```
Comment (AgentHagu) [inline packages/cli/test/functional/testUtil/compare.js:57]:
```suggestion
  actualPaths = filterPageVueRenderFiles(actualPaths);
  expectedPaths = filterPageVueRenderFiles(expectedPaths);
```

**Review by AgentHagu — CHANGES_REQUESTED** [review]
There's a minor issue with the current fix. Although `*.page-vue-render.js` files are correctly ignored by `.gitignore` and not committed, they are still generated locally whenever `npm run updatetest` is ran with changes to the code.

This causes `npm run test` to throw the following error:
image

The issue arises because the test comparison logic filters out `*.page-vue-render.js` from the actual output but not from the expected snapshot paths, which may now include these newly generated files. We can fix this by also filtering out `*.page-vue-render.js` from `expectedPaths` in case of these newly generated files.

Alternatively, we can try to prevent these files from being generated in the expected snapshot paths, but I'm not familiar with how feasible or practical this solution will be.

**Comment by AgentHagu** [comment]
> Checking file existence could be beneficial, but my rationale for completely removing the render files existence was to lower version history bloat for these render files, as well as reduce changes shown on PR diffs when updating tests. What do you think>

I see! In that case, I think the current solution should work best for us
