### PR TITLE
Fix: Uncaught exceptions cause a silent exit

### LINKED ISSUE #265: Show error message when aborting due to nunjucks error
Context: I have a need to generate several variations of the same site. As markbind doesn't have syntax to support conditional variations yet, I've resorted to using nunjucks code (on top of markbind) for the time being. [example](https://github.com/nus-cs2103/website-base/edit/master/se-book-adapted/chapters/architecture.md)

Current: If there is an error in nunjucks code (e.g., importing a file that doesn't exist), the build fails silently. Same applies to live preview.

Suggested: instead of failing silently, show some error information from nunjucks

### PR DESCRIPTION
**Pull request by amad-person**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Bug fix

Fixes #265, #610.

**What is the rationale for this request?**

Errors in building files with nunjucks (as well as uncaught exceptions) were causing a silent exit. This information should be shown to the user on the console. It was previously shown in the log file only. 

**What changes did you make? (Give an overview)**

Added a new [Console transport](https://github.com/winstonjs/winston/blob/master/docs/transports.md#console-transport) to winston for logging errors to the console.

Also passed the path parameter to `nunjucks.renderString()` as errors thrown by Nunjucks were not showing the file paths.

**Provide some example code that this change will affect:**

Add the following statement to any file: 

```
<!-- the following will cause an exception in Nunjucks -->
{% set error = " %}
```

Console output on `markbind build`:

```
error: uncaughtException: (/Users/aadyaamaddi/Desktop/BComp/Semester 6 1819/CS3281:2/markbind/docs/about.md) [Line 14, Column 19]
  expected block end in set statement date=Thu Feb 21 2019 10:22:03 GMT+0800 (Singapore Standard Time), pid=32358, uid=501, gid=20, cwd=/Users/aadyaamaddi/Desktop/BComp/Semester 6 1819/CS3281:2/markbind/docs, execPath=/usr/local/Cellar/node/11.10.0/bin/node, version=v11.10.0, argv=[/usr/local/Cellar/node/11.10.0/bin/node, /usr/local/bin/markbind, build], rss=85471232, heapTotal=64253952, heapUsed=37254224, external=2661243, loadavg=[2.04248046875, 2.189453125, 2.33935546875], uptime=310221
Template render error: (/Users/aadyaamaddi/Desktop/BComp/Semester 6 1819/CS3281:2/markbind/docs/about.md) [Line 14, Column 19]
  expected block end in set statement
    at Object.exports.prettifyError (/Users/aadyaamaddi/Desktop/BComp/Semester 6 1819/CS3281:2/markbind/src/lib/markbind/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/aadyaamaddi/Desktop/BComp/Semester 6 1819/CS3281:2/markbind/src/lib/markbind/node_modules/nunjucks/src/environment.js:472:27)
    at new_cls.renderString (/Users/aadyaamaddi/Desktop/BComp/Semester 6 1819/CS3281:2/markbind/src/lib/markbind/node_modules/nunjucks/src/environment.js:328:21)
    at Object.module.exports.renderString (/Users/aadyaamaddi/Desktop/BComp/Semester 6 1819/CS3281:2/markbind/src/lib/markbind/node_modules/nunjucks/index.js:80:14)
    at fs.readFile (/Users/aadyaamaddi/Desktop/BComp/Semester 6 1819/CS3281:2/markbind/src/lib/markbind/src/parser.js:508:36)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
```

### CODE REVIEW

File: src/lib/markbind/src/parser.js [hunk 1]
```diff
@@ -504,7 +505,8 @@ Parser.prototype.includeFile = function (file, config) {
       const { parent, relative } = calculateNewBaseUrls(file, config.rootPath, config.baseUrlMap);
       const userDefinedVariables = config.userDefinedVariablesMap[path.resolve(parent, relative)];
       const pageVariables = extractPageVariables(path.basename(file), data, userDefinedVariables, {});
-      const fileContent = nunjucks.renderString(data, { ...pageVariables, ...userDefinedVariables });
+      const fileContent = nunjucks.renderString(data, { ...pageVariables, ...userDefinedVariables },
+                                                { path: actualFilePath });
```
Comment (acjh) [inline src/lib/markbind/src/parser.js]: Move second argument to a line of its own, similar to above.

File: src/util/logger.js [hunk 2]
```diff
@@ -8,6 +8,13 @@ const DailyRotateFile = require('winston-daily-rotate-file');
 winston.configure({
   exitOnError: false,
   transports: [
+    new (winston.transports.Console)({
+      colorize: true,
+      handleExceptions: true,
+      humanReadableUnhandledException: true,
+      level: 'error',
+      showLevel: true,
+    }),
```
Comment (acjh) [inline src/util/logger.js]: Is this different from `console.error`? Should we remove that?

Comment (amad-person) [reply src/util/logger.js]: Do you mean from this line:

https://github.com/MarkBind/markbind/blob/1686253401a4ad6ef75f67dfab0e7adc5c93543e/src/lib/markbind/src/parser.js#L82

Comment (acjh) [reply src/util/logger.js]: No, this line:

https://github.com/MarkBind/markbind/blob/669325bcdefdb2b2d6ddb37b2ef6500e64555eac/src/util/logger.js#L33

Comment (amad-person) [reply src/util/logger.js]: The current mechanism of logging is as follows: 

We are using `logger.js` functions to print messages to the console with `console.log()` statements and a [winston-daily-rotate-file transport](https://github.com/winstonjs/winston-daily-rotate-file) set to level `debug` that writes messages to a log file. 

Nunjucks errors were not being logged to the console because we are not calling `logger.error()` explicitly in `nunjucks.renderString()` (as we don't have error handlers for these calls). Other errors do get printed to the console because we call `logger.error()` when we catch them.

However, nunjucks errors were being printed to the log file because of the winston-daily-rotate-file transport. 

If we want to remove `console.error` (and other `console.log` statements in `logger.js`), then we should a winston console transport with the level set to `debug`. There is an option to use custom formats (color, etc.) too.

Comment (yamgent) [reply src/util/logger.js]: Correct me if I am wrong, `nunjucks` is actually using `winston-daily-rotate-file` internally?

Comment (amad-person) [reply src/util/logger.js]: No, `nunjucks` itself doesn't use `winston-daily-rotate-file`. `winston-daily-rotate-file` is a storage device for logs (i.e. a transport) where all our logging output goes. Currently MarkBind only uses this transport. To display logs on the console **with winston** we should have added a Console transport to our winston configuration.

The reason any log messages are being shown on the console right now is because `logger.js` explicitly outputs them using `console.log` statements.

Comment (amad-person) [reply src/util/logger.js]: Hope this makes sense!

Comment (acjh) [reply src/util/logger.js]: 1. Where do we configure winston for nunjucks?

2. > If we want to remove `console.error` (and other `console.log` statements in `logger.js`), then we should use the winston console transport with the level set to `debug`.

   Why is level set to `error` insufficient to remove `console.error`?

Comment (amad-person) [reply src/util/logger.js]: > 1. Where do we configure winston for nunjucks?

If I'm not wrong, we are configuring winston only once in `logger.js` and using the logger instance in the rest of the application.

> 2. Why is level set to `error` insufficient to remove `console.error`?

For removing `console.error`, setting the level to `error` is sufficient. If we want to take it one step further and remove statements like `console.log(chalk.cyan('info: ') + text)` (i.e. for other levels too), `debug` would work.

Comment (acjh) [reply src/util/logger.js]: 1. So how does nunjucks use winston?

2. As asked in my first comment: *Should we remove that?*

Comment (amad-person) [reply src/util/logger.js]: > 1. So how does nunjucks use winston?

Our application as a whole uses winston, so all logging messages are handled by it. We don't need to configure nunjucks to use it, any message / uncaught exception from nunjucks will be logged automatically to _the log file_ (and only the log file, because that's the transport we have). 

> 2. As asked in my first comment: _Should we remove that?_

No we should not remove it, because we are calling `logger.error()` from other parts of the code. For example, our errorHandler uses it:

https://github.com/MarkBind/markbind/blob/6bbe1fa7d8a5eb02ff160050bc1fc088b9808f2e/src/Page.js#L766

Comment (acjh) [reply src/util/logger.js]: 1. How does our application use winston if not through logger?

2. Logger calls winston.

Comment (amad-person) [reply src/util/logger.js]: Our application does use winston through the logger, but we have also configured winston to handle logging uncaught exceptions. 
https://github.com/MarkBind/markbind/blob/6bbe1fa7d8a5eb02ff160050bc1fc088b9808f2e/src/util/logger.js#L15
That's how nunjucks errors were being logged to the log file.

Comment (acjh) [reply src/util/logger.js]: 1. Thanks for checking this. It answers the question originally raised by @yamgent.

2. How about this?

Comment (amad-person) [reply src/util/logger.js]: > 1. Let's set `winston.transports.Console` level to `'info'` and then remove `console.log` in `logger.error`, `logger.warn` and `logger.info`.

May I do these changes in this PR itself?

Comment (acjh) [reply src/util/logger.js]: Yes please.

**Comment by yamgent** [comment]
Console seems to be more noisy now though since we now print everything. :/

```
> markbind build
error: No config file found in parent directories of D:\GitHub\yamgent\markbind
error: uncaughtException: Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at Command.program.command.alias.option.description.action (D:\GitHub\yamgent\markbind\index.js:199:36)
    at Command.listener (D:\GitHub\yamgent\markbind\node_modules\commander\index.js:300:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (D:\GitHub\yamgent\markbind\node_modules\commander\index.js:635:12)
    at Command.parse (D:\GitHub\yamgent\markbind\node_modules\commander\index.js:457:21)
    at Object.<anonymous> (D:\GitHub\yamgent\markbind\index.js:210:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
```

**Comment by acjh** [comment]
Is that an actual error?

**Comment by amad-person** [comment]
> Is that an actual error?

Yep, it happens when you run `markbind build` in a directory with no `site.json`.

**Comment by yamgent** [comment]
> Is that an actual error?

Looks like I have accidentally discovered something worth fixing. :P Never mind my original comment then; I thought it was something that was previously printed on our own on the log.
