### PR TITLE
Bundle mermaid locally

### LINKED ISSUE #2667: Mermaid Script CORS issue
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

_No response_

### Tell us about your environment

Win 11

### MarkBind version

5.6.0

### Describe the bug and the steps to reproduce it

On the left is Vue3, right is Vue2. There seem to be a little issue with the rendering of the mermaid diagram.

_Originally posted by @IanCheah in https://github.com/MarkBind/markbind/issues/2622#issuecomment-2764379082_

Here is a screenshot:

Sometimes there is the CORS issue (left), sometimes there is no CORS issue (right). Both screenshots were taken of the same page at different times. Seems to be flaky.

Image

https://markbind-master.netlify.app/userguide/components/imagesanddiagrams#mermaid-diagrams

### Expected behavior

Should work.

### Anything else?

Seems to be quite a concerning regression actually, not sure why this is the case and why it was only spotted so late on by @IanCheah. 

However, since it is a CORS issue, if we directly support offline loading (#2548) and bundle it together it should totally resolve the issue.

### PR DESCRIPTION
**Pull request by Incogdino**
- Updated mermaid to use local version (V10.6.0) if a specific version is not specified.
- Updated tests.

**What is the purpose of this pull request?**

- [ ] Documentation update
- [X] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

Closes #2667 
Part of #2548

**Overview of changes:**
- Updated mermaid to use local version (V10.6.0) if a specific version
is not specified.
- Updated tests.

**Anything you'd like to highlight/discuss:**
We could explore upgrading mermaid to a later version in a future issue.

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**
Bundle mermaid locally

- Updated mermaid to use local version (V10.6.0) if a specific version
is not specified.
- Updated tests.

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [X] Added tests for bug fixes or features
- [X] Linked all related issues
- [X] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [x] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

### CODE REVIEW

File: packages/core/src/plugins/mermaid.ts [hunk 1]
```diff
@@ -1,15 +1,15 @@
 import cheerio from 'cheerio';
 import { PluginContext, FrontMatter } from './Plugin';
 
-const DEFAULT_CDN_ADDRESS = 'https://unpkg.com/mermaid@10/dist/mermaid.esm.min.mjs';
+const DEFAULT_MERMAID_PATH = './mermaidAssets/mermaid.min.js';
```
Comment (IanCheah) [inline packages/core/src/plugins/mermaid.ts:5]: Since we are specifying `DEFAULT_MERMAID_PATH` here. How about exporting this path and all other places reference this specific one.

So in other places instead of doing `./mermaidAssets/mermaid.min.js` we replace it with `DEFAULT_MERMAID_PATH`

File: packages/core/src/plugins/mermaid.ts [hunk 2]
```diff
@@ -1,15 +1,15 @@
...
```
Comment (Tim-Siu) [inline packages/core/src/plugins/mermaid.ts:4]: Can be simplified `const DEFAULT_MERMAID_PATH = 'mermaidAssets/mermaid.min.js';` as well. I used this in other plugins, but not sure which is the best practice.

File: packages/core/src/plugins/mermaid.ts (hunk 1 above)
Comment (Tim-Siu) [reply packages/core/src/plugins/mermaid.ts:5]: Seems like we don't need mermaid path at other files at the moment? It could be future-proving though.

**Review by Tim-Siu — APPROVED** [review]
An effective and straightforward fix. LGTM.

File: packages/core/src/plugins/mermaid.ts (hunk 1 above)
Comment (IanCheah) [reply packages/core/src/plugins/mermaid.ts:5]: I was suggesting that because I saw `./mermaidAssets/mermaid.min.js` being used in quite a few files under `test_site/expected`.

**Review by lhw-1 — APPROVED** [review]
Thanks for the fix @Incogdino! Apart from the issues brought up by other reviewers, LGTM

File: packages/core/src/plugins/mermaid.ts (hunk 1 above)
Comment (Incogdino) [reply packages/core/src/plugins/mermaid.ts:5]: Hmm I think those are auto generated when I run `npm run updatetest`

File: packages/core/src/plugins/mermaid.ts (hunk 2 above)
Comment (Incogdino) [reply packages/core/src/plugins/mermaid.ts:4]: Ill update it so that it stays consistent with the convention that we are already using. I don't think there is much difference either, except maybe using `./` is a bit more explicit in defining the path.

**Comment by gerteck** [comment]
Regressions Found:

image

Mermaid rendering does not work in panels (dynamic rendered content)

image

Some further work to refactor the logic would be good
