### PR TITLE
Fix siteNav example in documentation

### LINKED ISSUE #559: siteNav example in documentation is styled incorrectly
**Tell us about your environment**

* **MarkBind Version:** 1.16.0

**What did you do? Please include the actual source code causing the issue.**
In our [documentation for siteNav](https://markbind.github.io/markbind/userGuide/tweakingThePageStructure.html#site-navigation-menus), the main level links are incorrectly highlighted:

Incorrectly highlighted siteNav example

**What did you expect to happen?**
The correct example should not have any links highlighted:

Corrected siteNav example

The reason is because we style links in the siteNav to be `black` using the `id` (`#site-nav a:link`) in `site-nav.css`, but the example in the documentation is not in an element with `id='site-nav'`. Thus, it takes on the default colour for links (`a`) specified in `bootstrap.min.css` which is `#007bff`.

### PR DESCRIPTION
**Pull request by Xenonym**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Documentation update

Resolves #559.

**What is the rationale for this request?**
The documentation for the siteNav component and example code are styled incorrectly as they appear different from the actual siteNav. This may lead to user confusion.

**What changes did you make? (Give an overview)**
I added a `.site-nav` class that only has styles related to links and had both the example siteNav in the docs and the real siteNav use that class style, so that the styles of both will be consistent across both. I also changed the styles of the example code given so that they reflect the correct indentation to use.

**Testing instructions:**
1. Render a page with the siteNav. It should have the same styles as before.
2. Check the example siteNav render and code to ensure that they appear identical to the actual siteNav render and code.

### CODE REVIEW

File: src/Page.js [hunk 1]
```diff
@@ -487,7 +487,8 @@ Page.prototype.insertSiteNav = function (pageData) {
     siteNavDataSelector('navigation').replaceWith(formattedSiteNav);
   }
   // Wrap sections
-  const wrappedSiteNav = `<div id="${SITE_NAV_ID}">\n${siteNavDataSelector.html()}\n</div>`;
+  const wrappedSiteNav = `<div class="${SITE_NAV_ID}" id="${SITE_NAV_ID}">`
```
Comment (Chng-Zhi-Xuan) [inline src/Page.js]: Although having the same name for IDs and classes works perfectly fine. We should avoid it as it is prone to confusion.

Since the class styles the `<a>` tag only, we can rename the class to `site-nav__link` ? 

[Reference to BEM naming convention](https://medium.freecodecamp.org/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849)

File: docs/_markbind/variables.md [hunk 2]
```diff
@@ -1,7 +1,9 @@
-<span id="showBaseUrl">
+<span id="showBaseUrlCodeStyle">
 <code>{<span></span>{ baseUrl }}</code>
 </span>
 
+<span id="showBaseUrl">{<span></span>{ baseUrl }}</span>
```
Comment (Chng-Zhi-Xuan) [inline docs/_markbind/variables.md]: How about `<code>{<span></span>{ baseUrl }}</code>` -> `{{ showBaseUrlCode }}`

and `{<span></span>{ baseUrl }}` -> `{{ showBaseUrlText }}`

File: asset/css/site-nav.css [hunk 3]
```diff
@@ -114,7 +116,9 @@
 
 /* Hamburger button */
 
-.menu-top-bar, .menu-middle-bar, .menu-bottom-bar {
+.menu-top-bar, 
+.menu-middle-bar, 
+.menu-bottom-bar {
```
Comment (Chng-Zhi-Xuan) [inline asset/css/site-nav.css]: Good that you integrated the style from a review comment in #560

File: src/Page.js (hunk 1 above)
Comment (acjh) [reply src/Page.js]: `site-nav__link` would be directly applied to a `link` though.

https://seesparkbox.com/foundry/bem_by_example

Comment (Xenonym) [reply src/Page.js]: `site-nav__a`?

Comment (acjh) [reply src/Page.js]: I mean `site-nav__*` should go directly on the element.

The selector shouldn't be `.site-nav__a a { }`.

Comment (Xenonym) [reply src/Page.js]: I could change all generated links to follow `.site-nav__a`, but this probably means we should follow BEM in all our CSS files for consistency - is that what we want?

Alternatively, we could simply go with `.site-nav-link`/`.site-nav-a`.

Comment (acjh) [reply src/Page.js]: I'm open to either. @yamgent?

Comment (yamgent) [reply src/Page.js]: > I could change all generated links to follow `.site-nav__a`,

Let's go with this (i.e. the BEM naming convention).

File: asset/css/site-nav.css [hunk 4]
```diff
@@ -30,14 +30,14 @@
     -webkit-transition: 0.4s;
 }
 
-#site-nav a:active,
-#site-nav a:link,
-#site-nav a:visited {
+.site-nav__a:link,
+.site-nav__a:visited,
+.site-nav__a:active {
```
Comment (yamgent) [inline asset/css/site-nav.css]: Should be alphabetical order actually? :P

Comment (Chng-Zhi-Xuan) [reply asset/css/site-nav.css]: > a:hover MUST come after a:link and a:visited
> a:active MUST come after a:hover
> [Source](https://www.w3schools.com/css/css_link.asp)

So active being the last is correct.

Comment (acjh) [reply asset/css/site-nav.css]: That's for the case where the link states have different styles.
I'm okay with that order here, but let's add that reference as a comment.

Comment (Xenonym) [reply asset/css/site-nav.css]: I have added a link to the relevant section in the CSS standard for a more authoritative reference!
