### PR TITLE
Fix bug with dangling separator in `pageNav` when no title and nav headings given

### LINKED ISSUE #2055: Omit pageNav element if there are no navigable heading to remove unnecessary separator
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

_No response_

### Tell us about your environment

Windows 10

### MarkBind version

Master branch

### What did you do? Describe the bug

image

### Steps to reproduce

- `markbind init`
- go to `contents/topic1.md`
- add the following:
```
<frontmatter>
  layout: default.md
  pageNav: 2
</frontmatter>
```
- remove the default `# Topic 1`
- run `markbind serve -d`
- view the topic1 page

### Expected behavior

- If there are no navigable headings and no page title, the separator should not appear (the whole pagenav should be omitted)
- If there are page title, just show the page title

### Actual behavior

See screenshot above

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by domlimm**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [X] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Fixes #2055.

Add a strict check on the title and nav headings which are both type `string` to see if they are available from the `*.md` file. This allows for an early return which in turn omits the entire `pageNav` component on the page.

**Anything you'd like to highlight/discuss:**
Related to Issue #1954 and its PR #2054.

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**
Fix bug with dangling separator in pageNav section

The separator by CSS styling, border, appears when there is no title
and nav headings specified in the markdown files. This should not
appear.

Let's fix the logic when rendering the pageNav section to check
if there is a title and nav headings provided.

This logic will remove the unwanted separator.

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [X] Linked all related issues
- [ ] No unrelated changes

### CODE REVIEW

**Comment by ang-zeyu** [comment]
Does this enlarge the width of the main content area? We had some issues with that in the past, and decided to always render the page nav to ensure a consistent layout.

**Comment by domlimm** [comment]
Hello @ang-zeyu! Thanks for reviewing the PR!

I have just tested it on this branch, it seems like the entire page still has the `page-nav` component. So, I suppose the main content area width stays the same. Not sure if this is the best way to solve this issue. You mentioned CSS?

With the current change:
image

Before the current change:
image

As for #2054 was discussing with yongliang about this issue and the relation to #1954. But yes it seems as though omitting the element fixes the error in console. Maybe @tlylt can chime in on this. Not entirely certain also..

**Comment by ang-zeyu** [comment]
> CSS

Presumably the border is there as the content box of the page nav is taking up space, so we could try shifting the margins and paddings around to achieve the same look when there are headings then this fix when there aren't. But this might requires
 breaking changes to the user layout css file again... 😞 (but if not, it would be best)

This solution looks to be better in that case.

File: packages/core/src/Page/index.js [hunk 1]
```diff
@@ -432,6 +432,12 @@ class Page {
       this.collectNavigableHeadings(content);
       const pageNavTitleHtml = this.generatePageNavTitleHtml();
       const pageNavHeadingHTML = this.generatePageNavHeadingHtml();
+
+      if ((!pageNavTitleHtml || pageNavTitleHtml.length === 0)
+        && (!pageNavHeadingHTML || pageNavHeadingHTML.length === 0)) {
```
Comment (ang-zeyu) [inline packages/core/src/Page/index.js:437]: my understanding with #2054 is that the fix there is still ideal (dont render the data-bs attribute if we dont need it since we dont know whta might happen), even if this fixes it as a side effect as well.

---

the second .length checks here are unnecessary, empty strings are falsy.

Comment (tlylt) [reply packages/core/src/Page/index.js:437]: @domlimm yup as mentioned above, my PR should still stand as it tackles the bs attribute part. Your PR should be targeting just the #2055 part

Comment (domlimm) [reply packages/core/src/Page/index.js:437]: thanks for highlighting that! will make the change now

Comment (domlimm) [reply packages/core/src/Page/index.js]: @ang-zeyu @tlylt also, thanks so much for the help guys!

**Review by ang-zeyu — APPROVED** [review]

File: packages/core/src/Page/index.js (hunk 1 above)
Comment (ang-zeyu) [reply packages/core/src/Page/index.js]: > Proposed commit message: (wrap lines at 72 characters)

Let's add a message for the squashed commit

File: packages/core/src/Page/index.js [hunk 2]
```diff
@@ -432,6 +432,11 @@ class Page {
       this.collectNavigableHeadings(content);
       const pageNavTitleHtml = this.generatePageNavTitleHtml();
       const pageNavHeadingHTML = this.generatePageNavHeadingHtml();
+
+      if (!pageNavTitleHtml && !pageNavHeadingHTML) {
+        return '';
```
Comment (ang-zeyu) [inline packages/core/src/Page/index.js:437]: We can add in a simple functional test for this as well https://github.com/MarkBind/markbind/tree/master/packages/cli/test/functional
(there's a guide somewhere in the dev docs too if you need help writing one!)

**Review by ang-zeyu — CHANGES_REQUESTED** [review]

File: packages/core/src/Page/index.js (hunk 1 above)
Comment (domlimm) [reply packages/core/src/Page/index.js]: Will do!

File: packages/core/src/Page/index.js (hunk 2 above)
Comment (domlimm) [reply packages/core/src/Page/index.js:437]: Thanks zeyu, will do that asap 👍🏻

**Comment by domlimm** [comment]
hello guys, does anyone know why does this happen? i tried adding the functional test (could look at the stash at the bottom left) to this feat branch and running `npm run updatetest` was okay. but after rebasing the feat branch on the latest master it is not working anymore. not sure what's wrong 😓 

image

**Comment by tlylt** [comment]
> hello guys, does anyone know why does this happen? i tried adding the functional test (could look at the stash at the bottom left) to this feat branch and running `npm run updatetest` was okay. but after rebasing the feat branch on the latest master it is not working anymore. not sure what's wrong 😓

Are you saying after rebasing and then adding functional test and `npm run updatetest` won't work? After rebasing did you run `npm run setup` to just make sure all the setup stuff is correct? Can also try merging instead. I think if there's any conflict to the generated files its fine, I will typically do a `npm run updatetest` and then check in the latest generated files, which should be the correct version

**Comment by domlimm** [comment]
thank you so much for the help again yongliang! yes i missed that out.. will keep all these in mind!

i have added the test relevant to the bug fix. ready for your review please, and thank you!

File: packages/core/src/Page/index.js (hunk 2 above)
Comment (tlylt) [reply packages/core/src/Page/index.js:439]: @domlimm could we add one more test for having only the pageNavTitle and it still works as expected?

Comment (domlimm) [reply packages/core/src/Page/index.js:439]: sure!

File: packages/cli/test/functional/test_site/testPageNavWithOnlyTitle.md [hunk 3]
```diff
@@ -0,0 +1,11 @@
+<frontmatter>
+  layout: default.md
+  pageNav: 1
```
Comment (tlylt) [inline packages/cli/test/functional/test_site/testPageNavWithOnlyTitle.md:3]: Since pageNav is 1 and there's a H1 heading, is this example containing only the title?

Comment (domlimm) [reply packages/cli/test/functional/test_site/testPageNavWithOnlyTitle.md:3]: That's a good point. It contains title and the H1 heading. Sorry about that! Let me fix it now

Comment (domlimm) [reply packages/cli/test/functional/test_site/testPageNavWithOnlyTitle.md:3]: thanks yongliang!

It should look like this:

image

**Review by tlylt — APPROVED** [review]
LGTM. @domlimm thanks for the fixes
