### PR TITLE
Fix site-nav.css not being added when layout contains site nav

### LINKED ISSUE #528: Specifying layouts in a Page's front matter do not insert required CSS files for site navigation
* **MarkBind Version:** 1.15.2

**Cause**

The problem resides within Page.prototype.prepareTemplateData. If a `siteNav` is not explicitly declared within the `frontmatter` of a page, the associated CSS files will not be inserted into the page.

Bug found in #527

### PR DESCRIPTION
**Pull request by marvinchin**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [x] Bug fix

Fixes #528.

**What is the rationale for this request?**

When a page has a site nav specified in the layout, but not in the frontmatter, the site-nav.css file is not added to the site. This causes the styling of the side nav to break.

**What changes did you make? (Give an overview)**

- [x] Abstract method to get the path to the site nav file from `insertSiteNav`
- [x] Use abstracted method `getSiteNavPath` to check if a site nav is specified in either layout or frontmatter when preparing template data

**Is there anything you'd like reviewers to focus on?**

~~By default, the default layout contains a blank `navigation.md` file. The site-nav.css file is thus added even though the `navigation.md` file is empty - is this behaviour okay?~~

After updating the logic to use a flag instead, we are able to avoid this issue as we only update the flag after checking that the file is not empty.

**Testing instructions:**

See instructions in #739. The site nav should be styled correctly.

**Proposed commit message: (wrap lines at 72 characters)**

When passing data to the page template, the siteNav variable only checks
for the existence of the site nav specified in the frontmatter. The
site-nav.css file is thus only added when the site nav is specified in
the frontmatter.

When a page has a layout with a site nav, but no site nav is specified
in the frontmatter, the site-nav.css file is not added, which causes the
styling of the site nav to break.

Let's update the logic when forming template data to check for the
existence of a site nav in the template when determining the value of
the siteNav variable.

### CODE REVIEW

**Comment by Chng-Zhi-Xuan** [comment]
I briefly looked through, here are some comments

> By default, the default layout contains a blank navigation.md file. The site-nav.css file is thus added even though the navigation.md file is empty - is this behaviour okay?

In my opinion, if the user has a `navigation.md` file in the layouts, we should expect that the user intends to use the `site-nav`. Although we can make it more user friendly by using a better initial template rather than a blank file. 

We might also want to insert notes / tips into the `Layouts` section to inform users to delete certain files if you do not want to use them. 

**Implementation comments**

- Your implementation would require 2 calls to `this.getSiteNavPath()` when generating a page. 

To streamline this, would it be better if you just changed a boolean page variable after `this.getSiteNavPath()` is called, then use the same variable for the `siteNav` value within `prepareTemplateData` ?

**Comment by marvinchin** [comment]
Thanks for pointing that out!

I was trying to avoid the use of a global flag because it introduces some coupling between places that modify the flag, and those that read it (in this case, between `insertSiteNav` and `prepareTemplateData`).

As `getSiteNavPath` involves a (comparatively more costly) fs operation, and I don't forsee any other places where the flag would be modified, it might be more efficient to use a global flag as you suggested. I'll make the changes in a bit! 🙂

**Comment by marvinchin** [comment]
> By default, the default layout contains a blank `navigation.md` file. The site-nav.css file is thus added even though the `navigation.md` file is empty - is this behaviour okay?

After updating the logic to use a flag instead, we are able to avoid this issue as we only update the flag after checking that the file is not empty.

File: src/Page.js [hunk 1]
```diff
@@ -581,6 +584,7 @@ Page.prototype.insertSiteNav = function (pageData) {
   if (siteNavContent === '') {
     return pageData;
   }
+  this.hasSiteNav = true;
```
Comment (Chng-Zhi-Xuan) [inline src/Page.js]: Since you only modify the flag to be true at this point. If you delete the `navigation.md` (Or blank the contents) from the layouts folder, the `site-nav` will still appear in the `markbind serve` preview. Even though MarkBind correctly detected `navigation.md` has changed.

The only correct behaviour in this code is changing `navigation.md` slightly and the changes will reflect in the `markbind serve` preview.

**Suggestion**
Explicitly set the flag to false in the if statements above for it to function properly when in preview mode.

File: src/Page.js [hunk 2]
```diff
@@ -87,6 +87,9 @@ function Page(pageConfig) {
   this.keywords = {};
   this.navigableHeadings = {};
   this.pageSectionsHtml = {};
+
+  // flag to indicate whether this page has a site nav
```
Comment (Chng-Zhi-Xuan) [inline src/Page.js]: A quick search shows majority of inline comments have capitalised starting character (although not all).

**Comment by marvinchin** [comment]
@Chng-Zhi-Xuan I've made the requested changes!

**Comment by damithc** [comment]
Seems to be working. Good work!
