### PR TITLE
Remove padding top from navbar site logo

### LINKED ISSUE #1895: Off-center NavBar items
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Any related issues?

_No response_

### Tell us about your environment

MacOS Monterey

### MarkBind version

3.1.1

### What did you do? Describe the bug

The NavBar items are not vertically centered. 
Screenshot 2022-04-12 at 12 43 57 AM

Annotated image: The centreline of the site logo (red box) should align with the centre of the NavBar items (blue box). However, the nav items are a little too low.

Screenshot 2022-04-12 at 12 43 57 AM 2

### Steps to reproduce

Open MarkBind in a window that is small enough such that the lower navbar appears, but large enough such that the NavBar remains expanded (items don't collapse into a new row).

### Expected behavior

Site logo and nav items should be vertically centered. Green box shows the correct (vertically centered) position of the nav items: 
Screenshot 2022-04-12 at 12 43 57 AM 2

### Actual behavior

(Screenshot above)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by elroygohjy**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] Others, please explain:

**Overview of changes:**
Resolves #1895

**Anything you'd like to highlight / discuss:**
Remove padding top from .nav-left class selector.

Before:
image
After:
image

**Testing instructions:**
Inspect navbar site logo and it is now align-center with other navbar elements.

**Proposed commit message: (wrap lines at 72 characters)**
`Remove padding top from site logo`

### CODE REVIEW

**Comment by damithc** [comment]
Thanks for the PR @elroygohjy Indeed the 'after' one looks better.
🤔  hmmm... are we sure we want to change a general navbar style like this? It will affect every MarkBind site. Could the problem lie with the specific logo image rather than the style?

**Comment by elroygohjy** [comment]
Hi prof, I have double checked, the problem is not caused by the logo design, but I have made a implementation error on my end as my fix is flawed.
image
The actual problem actually lies in .navbar-brand having an additional padding-top of 5px, which causes the logo to be unable to align center with the rest of the navbar elements.

**Comment by elroygohjy** [comment]
Hello prof, 
This problem is definitely not caused by the logo used.
So, current logo height is 20px as shown:
image
But, there is addition 5px of padding-top that is hidden, although the height of navbar-brand should be 30px inclusive of padding.
image
This is the reason why the logo is not aligning.
My current implementation failed to understand this problem, i will be creating a new commit that removes this 5px of padding and to center the logo.

File: packages/vue-components/src/Navbar.vue [hunk 1]
```diff
@@ -363,12 +363,18 @@ export default {
         display: inline-block;
     }
 
+    .navbar-brand > img,
+    svg {
```
Comment (jonahtanjz) [inline packages/vue-components/src/Navbar.vue:367]:
```suggestion
    .navbar-brand > svg {
```

Should this have the `.navbar-brand` selector as well? If not this will select all `svg` elements.

**Review by jonahtanjz — COMMENTED** [review]
Thanks for investigating and fixing this @elroygohjy. Nice work :)

Just one question, the rest looks good :)

**Review by jonahtanjz — APPROVED** [review]
LGTM 👍
