### PR TITLE
Fix expected help message to show header

### LINKED ISSUE #644: -h/--help option does not output the banner
**Tell us about your environment**

* **MarkBind Version:** 1.17.1

**What did you do? Please include the actual source code causing the issue.**
I ran `markbind -h/--help` /  `markbind <option> -h/--help`.

**What did you expect to happen?**
Like other commands, `-h/--help` should output with the header:
```
  __  __                  _      ____    _               _
 |  \/  |   __ _   _ __  | | __ | __ )  (_)  _ __     __| |
 | |\/| |  / _` | | '__| | |/ / |  _ \  | | | '_ \   / _` |
 | |  | | | (_| | | |    |   <  | |_) | | | | | | | | (_| |
 |_|  |_|  \__,_| |_|    |_|\_\ |____/  |_| |_| |_|  \__,_|

 v1.17.1
 
  Usage: markbind <command>


  Options:

    -V, --version  output the version number
    -h, --help     output usage information


  Commands:

    init|i [root]                      init a markbind website project
    serve|s [options] [root]           build then serve a website from a directory
    deploy|d [options]                 deploy the site to the repo's Github pages.
    build|b [options] [root] [output]  build a website
```
**What actually happened? Please include the actual, raw output.**
The help information was printed without a header:
```
PS C:\Users\pzy5a\Desktop\testbind> markbind -h

  Usage: index  <command>


  Options:

    -V, --version  output the version number
    -h, --help     output usage information


  Commands:

    init|i [root]                      init a markbind website project
    serve|s [options] [root]           build then serve a website from a directory
    deploy|d [options]                 deploy the site to the repo's Github pages.
    build|b [options] [root] [output]  build a website
```
This was also the case for option help eg. `markbind serve -h/--help`.
Also, the usage information is improperly formatted; it should be `markbind <command>` instead of `index  <command>` (note the extraneous space).

### PR DESCRIPTION
**Pull request by madanalogy**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Bug Fix

Resolves #644 

**What is the rationale for this request?**

Improves consistency of markbind's CLI interface.

**What changes did you make? (Give an overview)**

I added a function to handle help messages for use with commander. The function prints the banner and is used in commander's ```helpOption()``` method.

**Provide some example code that this change will affect:**

```
function handleHelp(txt) {
  printHeader();
  logger.log('');
  return txt;
}
program
  .helpOption('-h, --help', handleHelp('output usage information'));
```

**Is there anything you'd like reviewers to focus on?**

Updating of the commander module to latest version, whether it was done properly.

**Testing instructions:**

From the main working directory, run ```node index.js -h```

**Proposed commit message: (wrap lines at 72 characters)**

Fixes CLI help command.

### CODE REVIEW

**Comment by madanalogy** [comment]
Thank you for the information and suggestion :)

I have reverted the changes to the json files and implemented an override for outputHelp (instead of my earlier initial implementation). I will also be editing the PR title, thanks again for pointing me in the right direction!

File: index.js [hunk 1]
```diff
@@ -37,11 +37,27 @@ function handleError(error) {
   process.exitCode = 1;
 }
 
+// The following code block overrides commander's outputHelp()
```
Comment (yamgent) [inline index.js]: It would be better if the comment mentions the _why_ (the reason for overriding) as well.

You should mention that we want to customize the help message with MarkBind's header, but commander.js doesn't provide any API to customize the help message.

```js
// We want to customize the help message to print MarkBind's header,
// but commander.js does not provide an API directly for doing so.
// Hence we override commander's outputHelp() completely.
```

File: index.js [hunk 2]
```diff
@@ -37,11 +37,27 @@ function handleError(error) {
...
+  if (!cb) {
+    // eslint-disable-next-line no-param-reassign
+    cb = function (passing) {
+      return passing;
+    };
+  }
+  process.stdout.write(cb(this.helpInformation()));
+  this.emit('--help');
+};
+module.exports = program;
```
Comment (yamgent) [inline index.js]: Is this line needed? I don't think anybody outside `index.js` uses the `program` variable inside here.

File: index.js [hunk 3]
```diff
@@ -37,11 +37,27 @@ function handleError(error) {
...
+delete program.outputHelp;
+program.outputHelp = function (cb) {
+  printHeader();
+  if (!cb) {
+    // eslint-disable-next-line no-param-reassign
+    cb = function (passing) {
+      return passing;
+    };
+  }
+  process.stdout.write(cb(this.helpInformation()));
```
Comment (yamgent) [inline index.js]: I was wondering whether it would be even better if we just shadow the original method, and utilise it in our new method. This way, we do not have to duplicate the original method's logic at all, in case there's an update to the commander's logic when we move to a new version:

```js
program.defaultOutputHelp = program.outputHelp;
program.outputHelp = function (cb) {
  printHeader();
  this.defaultOutputHelp(cb);
};
```

**Comment by madanalogy** [comment]
Thank you for the suggestions! I have changed the implementation to shadow instead of replace and updated the code comment. I have also rebased and squashed my commits.
