### PR TITLE
Fix page title prefix get repeated at every live reload

### LINKED ISSUE #233: page title prefix get repeated at every live reload
Steps:
1. specify a title prefix in site.json e.g., `"titlePrefix": "Sandbox"`
2. markbind serve
3. edit some code and save, to trigger a live reload.

Observation: every live reload causes a repetion of the page title prefix. 

image
image

### PR DESCRIPTION
**Pull request by yamgent**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Bug fix

Fixes #233.

**What is the rationale for this request?**
While the website is running live through `markbind serve`, modifying a page causes the page title to re-prepend the title prefix to the title. Therefore, reloading the page three times will cause three title prefixes to appear on the page title for example.

**What changes did you make? (Give an overview)**
Moved the prefix prepending logic to the `prepareTemplateData()` function so that the title prefix only gets added in at the render stage, rather than at the page (re-)processing stage.

**Provide some example code that this change will affect:**

Before | After
---- | ----
title - before | title - after

**Is there anything you'd like reviewers to focus on?**
NIL

**Testing instructions:**
1. Run `markbind serve` on a website with a `titlePrefix` set (e.g. `"titlePrefix": "Prefix"`).
2. Modify the page multiple times (change, save, change, save, ...).
3. The new page should still have one title prefix (e.g. "Prefix - XXXXXX").

### CODE REVIEW

File: lib/Page.js [hunk 1]
```diff
@@ -107,22 +111,13 @@ Page.prototype.collectFrontMatter = function (includedPage) {
...
-    }
   } else {
     // Page is addressable but no front matter specified
-    const formattedTitle = this.titlePrefix
-      ? this.titlePrefix + (this.title ? TITLE_PREFIX_SEPARATOR + this.title : '')
-      : this.title;
     this.frontMatter = {
       src: this.src,
-      title: formattedTitle,
+      title: (this.title || ''),
```
Comment (acjh) [inline lib/Page.js]: Remove parentheses.

File: lib/Page.js [hunk 2]
```diff
@@ -107,22 +111,13 @@ Page.prototype.collectFrontMatter = function (includedPage) {
...
     };
   }
-  this.title = this.frontMatter.title;
```
Comment (acjh) [inline lib/Page.js]: We should sync `this.title`.

File: lib/Page.js [hunk 3]
```diff
@@ -67,12 +67,16 @@ function unique(array) {
 }
 
 Page.prototype.prepareTemplateData = function () {
+  const titleWithPrefix = this.titlePrefix
+    ? this.titlePrefix + (this.frontMatter.title ? TITLE_PREFIX_SEPARATOR + this.frontMatter.title : '')
+    : this.frontMatter.title;
```
Comment (acjh) [inline lib/Page.js]: - How about: `const prefixedTitle`
- Use `this.title`.

**Comment by yamgent** [comment]
* Made changes w.r.t. review comments
* Cleaned up the second commit message's language
