### PR TITLE
Fix search bar to include frontmatter keywords

### LINKED ISSUE #2026: Keywords included in a page's frontmatter are not taken into account in the search bar's results
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#311

### Tell us about your environment

Mac

### MarkBind version

v4

### What did you do? Describe the bug

Adding keywords to a page's frontmatter should cause it to be included in the search results if that keyword is searched for. However, this does not seem to be the case (see steps to reproduce).

### Steps to reproduce

I added a new page as below:
```
<span id="title" class="d-none">Formatting Contents</span>

<frontmatter>
  title: "Formatting Contents"
  keywords: plugin
</frontmatter>
```

Following which, I searched for `plugin` in the search bar, which led to this result:
Screenshot 2022-09-02 at 12 29 42 PM

### Expected behavior

The `Formatting Contents` page should have shown up as a search result as one of its keywords was searched for.

### Actual behavior

The `Formatting Contents` page did not show up.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by itsyme**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Resolves #2026. Changes `writeSiteData` in `Site/index.js` to include writing frontmatter so that `Searchbar.vue` can access keywords in frontmatter to search.

**Anything you'd like to highlight/discuss:**
There is an alternative implementation of writing only including frontmatter keywords in `writeSiteData`.
Also, need to update `page.frontMatter` to `page.frontmatter` in `Site/index.js` after merging #2049.

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [ ] Linked all related issues
- [ ] No unrelated changes

### CODE REVIEW

File: packages/vue-components/src/Searchbar.vue [hunk 1]
```diff
@@ -124,8 +124,9 @@ export default {
           src,
           title,
           headingKeywords,
+          frontmatter,
         } = entry;
-        const keywords = entry.keywords || '';
+        const keywords = frontmatter.keywords || '';
```
Comment (ang-zeyu) [inline packages/vue-components/src/Searchbar.vue:129]: Do we have a guess why this was `entry.keywords` initially?

Our old repo that contains much of this file's history is also available [here](https://github.com/MarkBind/vue-strap.git) so this could be a good exercise in `git blame`-ing your way through the diff.

Comment (itsyme) [reply packages/vue-components/src/Searchbar.vue:129]: In my opinion, it was `entry.keywords` initially to prepare the `Searchbar` to include frontmatter keywords since there was no `keywords` property in the entry object. This was done to make it easier to implement the inclusion of frontmatter keywords in `Searchbar`. I came to this conclusion after looking through the history of commits and entry never contained a `keywords` property from the beginning of the commit history.

File: packages/core/src/Site/index.js [hunk 2]
```diff
@@ -1432,6 +1432,7 @@ class Site {
           title: page.title,
           headings: page.headings,
           headingKeywords: page.keywords,
+          frontmatter: page.frontMatter,
```
Comment (ang-zeyu) [inline packages/core/src/Site/index.js:1435]: I'm thinking we should add in just the keywords for now, I don't see the other properties being of use. What do you think?

File: packages/cli/test/functional/test_site/expected/siteData.json [hunk 3]
```diff
@@ -5,7 +5,12 @@
       "src": "bugs/index.md",
       "title": "Open Bugs",
       "headings": {},
-      "headingKeywords": {}
+      "headingKeywords": {},
+      "frontmatter": {
+        "title": "Open Bugs",
+        "globalOverrideProperty": "Overridden by global override",
+        "globalAndFrontMatterOverrideProperty": "Overridden by global override"
+      }
```
Comment (ang-zeyu) [inline packages/cli/test/functional/test_site/expected/siteData.json:13]: Let's add in a [functional test](https://markbind.org/devdocs/devGuide/workflow.html#updating-functional-tests) into any one of the test pages for this to generate a page with `"frontmatter": { "keywords": ... }"`.

File: packages/vue-components/src/Searchbar.vue (hunk 1 above)
Comment (ang-zeyu) [reply packages/vue-components/src/Searchbar.vue:129]: > I came to this conclusion after looking through the history of commits and entry never contained a keywords property from the beginning of the commit history.

Agreed, this should be good enough. Thanks for investigating!

File: packages/core/src/Site/index.js (hunk 2 above)
Comment (itsyme) [reply packages/core/src/Site/index.js:1435]: I agree! I will make the necessary changes in the next commit!

File: packages/cli/test/functional/test_site/expected/siteData.json (hunk 3 above)
Comment (itsyme) [reply packages/cli/test/functional/test_site/expected/siteData.json:13]: Alright! I will add a functional test in my next commits!

**Review by ang-zeyu — APPROVED** [review]

**Comment by tlylt** [comment]
@all-contributors please add @itsyme for code, docs
