### PR TITLE
Fix anchors for panel headers

### LINKED ISSUE #442: Show anchor icons for heading inside panels
**Tell us about your environment**

* **MarkBind Version:** 1.13.0

**What did you do? Please include the actual source code causing the issue.**
Followup from https://github.com/MarkBind/markbind/issues/426#issuecomment-425449396.

```html
<panel header="# Some heading">
    ... Some content here ...
</panel>
```

**What did you expect to happen?**
An anchor icon appears right beside the heading.

**What actually happened? Please include the actual, raw output.**
No anchor icon show up beside the heading.

### PR DESCRIPTION
**Pull request by jamos-tay**
**What is the purpose of this pull request? (put "X" next to an item, remove the rest)**

• [X] Bug fix

Fixes #442 

**What is the rationale for this request?**

Anchors were not being generated for panel headers, and in a previous version do not redirect to the page when clicked.

**What changes did you make? (Give an overview)**

Anchors should now be generated for panel headers correctly.

The panel headers are stored in the panel's `header` attribute and rendered by vue, so headings weren't being picked up by `Page`. I worked around this by checking all panels for the `header` attribute and adding the anchor html there.

As for the links not working previously (see https://github.com/MarkBind/markbind/issues/442#issuecomment-425638038), I added some code to `setup.js` to manually redirect the page when an anchor is clicked, it seems to be working as expected now.

### CODE REVIEW

**Comment by jamos-tay** [comment]
The tests are passing locally on my machine (windows) but for some reason Travis seems to be failing.

Somehow when rendered on Travis the block of code I added causes the `src` attribute of panels to change, all the `\` are converted to `/`:

image

File: test/test_site/testUtil/diffHtml.js [hunk 1]
```diff
@@ -89,7 +89,7 @@ const diffHtml = (expected, actual) => {
       insidePath = true;
     }
 
-    if (isDiff(part) && !insidePath) {
+    if (isDiff(part) && !insidePath && !isPathSeparatorDiff(part.value)) {
```
Comment (nicholaschuayunzhi) [inline test/test_site/testUtil/diffHtml.js]: The change here allows for this situation to pass:
`expected.html`
```html
<div> \ </div>
```

`actual.html`
```html
<div> / <div>
```

**Comment by nicholaschuayunzhi** [comment]
> Somehow when rendered on Travis the block of code I added causes the src attribute of panels to change, all the \ are converted to /.

The reason is because the Travis is running a unix env and the path separator generated will be `/` whereas on Windows, it will be `\`.

As for the diff that is being shown, I would think my diffing code will account for that and not trigger an error. Sorry about that 🙏. I will help to look into the matter.

Also see my comment about your fix!

**Comment by nicholaschuayunzhi** [comment]
@jamos-tay The fix has been merged to master, you can go ahead and rebase on master and also drop commits `d6e6851` and `eb2f83a`

**Comment by jamos-tay** [comment]
Sure, updated 👍

**Comment by yamgent** [comment]
Seems OK, but user-usability wise, I actually expected the anchor to have appeared when the mouse is inside the panel's header box, but as of now you must hover the mouse inside the header text in order to reveal it.

anchor

**Comment by jamos-tay** [comment]
Yeah... the dimensions of the header seems to be different for headers in panels.

I'll try and find a fix

**Comment by jamos-tay** [comment]
@yamgent Hey, think it should be fixed now.

There's still a minor nit where the anchor will disappear if the user hovers over the header text first, then moves the mouse right until the empty space (basically `mouseleave` gets triggered for the header), but fixing it would be quite troublesome and I think it's small enough to ignore.

File: test/test_site/expected/markbind/js/setup.js [hunk 2]
```diff
@@ -24,12 +24,17 @@ function setupAnchorVisibility() {
       jQuery(this).children('.fa.fa-anchor').hide();
     });
   });
+  jQuery('.fa-anchor').each((index, anchor) => {
```
Comment (yamgent) [inline test/test_site/expected/markbind/js/setup.js]: Remember to update the content of `test/test_site/expected/markbind/js/setup.js` with the new code that you have.
