### PR TITLE
Rebase reference for static includes that target a div

### LINKED ISSUE #94: static includes that target a div: re-basing links doesn't work
Given this code `[link]({{baseUrl}}/common/print.html)` in `book/usage.md` which is included in `schedule\overview\about.md` 
image
image

`<include src="../../book/about/usage.md"/>` : link works
`<include src="../../book/about/usage.md#printing"/>` : produces a broken link
`<include src="../../book/about/usage.md#printing" dynamic/>` : link works

Looks like re-basing links doesn't work for static includes that targets a div (rather than entire page)

### PR DESCRIPTION
**Pull request by acjh**
Fixes #94

### CODE REVIEW

File: lib/parser.js [hunk 1]
```diff
@@ -275,7 +276,7 @@ Parser.prototype._trimNodes = function (node) {
   }
 };
 
-Parser.prototype.includeFile = function (file, cb) {
+Parser.prototype.includeFile = function (file, cb, config) {
```
Comment (Gisonrg) [inline lib/parser.js]: I am thinking about deprecating the callback for the API and use Promise only, and I don't think we are still using callback anywhere in the codebase, so I think it's safe to change to put `config` after the `file` parameter here (do a check before you do so) :)  
Let's create an issue and get rid of callback in a separate PR.

Comment (acjh) [reply lib/parser.js]: Checked and changed!
